language: node_js
cache:
  directories:
    - '$HOME/.npm'
notifications:
  email: false
node_js:
  - 'node'
install:
  - npm ci
script:
  - npm run lint
  - npm run test:coverage
  - npm run build
after_success:
  - npx codecov
deploy:
  - provider: script
    script: npx now -e GITHUB_CLIENT_SECRET --token $NOW_TOKEN && npx now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true