language: node_js
cache:
  directories:
    - '$HOME/.npm'
notifications:
  email: false
node_js:
  - 'node'
install:
  - npm ci
script:
  - npm run lint
  - npm run test
  - npm run build
deploy:
  - provider: script
    script: npx now --public --token $NOW_TOKEN && npx now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true